# Generated by Django 3.2 on 2021-04-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=1500)),
                ('url', models.CharField(max_length=1500)),
                ('status_code', models.CharField(max_length=3)),
                ('response_size', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
