# Generated by Django 3.2 on 2021-04-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bq', '0002_auto_20210420_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test_1',
            options={'verbose_name': 'LogEntry', 'verbose_name_plural': 'LogEntry'},
        ),
    ]
