# Generated by Django 3.2 on 2021-04-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bq', '0003_alter_test_1_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_1',
            name='date',
            field=models.CharField(max_length=50, verbose_name='Дата и время запроса'),
        ),
        migrations.AlterField(
            model_name='test_1',
            name='ip',
            field=models.CharField(max_length=50, verbose_name='ip Адрес'),
        ),
        migrations.AlterField(
            model_name='test_1',
            name='method',
            field=models.CharField(max_length=1500, verbose_name='Метод запроса'),
        ),
        migrations.AlterField(
            model_name='test_1',
            name='response_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Размер ответа'),
        ),
        migrations.AlterField(
            model_name='test_1',
            name='status_code',
            field=models.CharField(max_length=4, verbose_name='Код ответа'),
        ),
        migrations.AlterField(
            model_name='test_1',
            name='url',
            field=models.CharField(max_length=1500, verbose_name='URL запроса'),
        ),
    ]
